In [ ]:
#Name : Mitali Mishra
#Roll no : 154
#Problem Statement : Assignment based on Numpy arrays and functions (Numpy Library)

In [2]:
import numpy as np #Import numpy library
print(np.__version__) #Check Version

2.3.2


In [50]:
import numpy as np
arr=np.array([[4,2,6],[8,1,7],[9,3,5],[2,7,5]])
print(arr) #printing array


[[4 2 6]
 [8 1 7]
 [9 3 5]
 [2 7 5]]


In [51]:
arr=np.array([[4,2,6],[8,1,7],[9,3,5],[2,7,5]])
print(arr.shape) #shape(diamensions) of array

(4, 3)


In [52]:

arr=np.array([[4,2,6],[8,1,7],[9,3,5],[2,7,5]])
print(arr.dtype) #datatype of array

int64


In [23]:
import numpy as np
arr=np.array([[4,2,6],[8,1,7],[9,3,5],[2,7,5]])
print(arr)
print(arr.shape)
print(arr.dtype)

[[4 2 6]
 [8 1 7]
 [9 3 5]
 [2 7 5]]
(4, 3)
int64


In [53]:
print(arr.reshape(3,4)) #reshape array


[[4 2 6 8]
 [1 7 9 3]
 [5 2 7 5]]


In [ ]:
print(np.sort(arr,axis=0)) #sort the array column wise
print(np.sort(arr,axis=1)) #sort the array row wise

[[2 1 5]
 [4 2 5]
 [8 3 6]
 [9 7 7]]
[[2 4 6]
 [1 7 8]
 [3 5 9]
 [2 5 7]]


In [ ]:
print(arr.min()) #minimum value

1


In [ ]:
print(arr.max()) #maximum value

9


In [ ]:
print(arr.swapaxes(0,1)) #swap elements by index


[[4 8 9 2]
 [2 1 3 7]
 [6 7 5 5]]


In [39]:
arr1=np.zeros((9,8),dtype="int")
print(arr1)
print(arr1.shape)
print(arr1.dtype)


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
(9, 8)
int64


In [41]:
import numpy as np
zero_arr=np.zeros(8)
print(zero_arr)
zero_arr.dtype
zero_arr.astype(np.int32)

[0. 0. 0. 0. 0. 0. 0. 0.]


array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [ ]:
np.linspace(arr,1,11) 

array([[[4. , 2. , 6. ],
        [8. , 1. , 7. ],
        [9. , 3. , 5. ],
        [2. , 7. , 5. ]],

       [[3.7, 1.9, 5.5],
        [7.3, 1. , 6.4],
        [8.2, 2.8, 4.6],
        [1.9, 6.4, 4.6]],

       [[3.4, 1.8, 5. ],
        [6.6, 1. , 5.8],
        [7.4, 2.6, 4.2],
        [1.8, 5.8, 4.2]],

       [[3.1, 1.7, 4.5],
        [5.9, 1. , 5.2],
        [6.6, 2.4, 3.8],
        [1.7, 5.2, 3.8]],

       [[2.8, 1.6, 4. ],
        [5.2, 1. , 4.6],
        [5.8, 2.2, 3.4],
        [1.6, 4.6, 3.4]],

       [[2.5, 1.5, 3.5],
        [4.5, 1. , 4. ],
        [5. , 2. , 3. ],
        [1.5, 4. , 3. ]],

       [[2.2, 1.4, 3. ],
        [3.8, 1. , 3.4],
        [4.2, 1.8, 2.6],
        [1.4, 3.4, 2.6]],

       [[1.9, 1.3, 2.5],
        [3.1, 1. , 2.8],
        [3.4, 1.6, 2.2],
        [1.3, 2.8, 2.2]],

       [[1.6, 1.2, 2. ],
        [2.4, 1. , 2.2],
        [2.6, 1.4, 1.8],
        [1.2, 2.2, 1.8]],

       [[1.3, 1.1, 1.5],
        [1.7, 1. , 1.6],
        [1.8, 1.2, 1.4],
       

In [46]:
arr=np.zeros((5,7))
print(arr)
arr1=np.zeros((5,7),dtype="int")
print(arr1)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [49]:
arr=np.ones((9,2))
print(arr)
arr1=np.ones((5,8),dtype="int")
print(arr1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


In [54]:
arr1=np.array([1,2,3,4,5,6,7,8,9]) #creating 1 dimensional array
print(arr1)
print(arr1.ndim) #prints dimension of array. Here array is 1 dimensional
print(arr1.dtype) #prints datatype of array
print(arr1.size) #prints no. of elements in array

[1 2 3 4 5 6 7 8 9]
1
int64
9


In [55]:
arr2=np.array([[1.,2.,3.],[5.,6.,7.]]) # creating array 2 dimensional array
print(arr2)
print(arr2.ndim) # Here array is 2 dimensional
print(arr2.dtype) 
print(arr2.size)
print(arr2.shape) #prints (no. of rows,no. of columns) in an array

[[1. 2. 3.]
 [5. 6. 7.]]
2
float64
6
(2, 3)


In [56]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,22,55]]]) #creating 3 dimensional array
print(arr3)
print(arr3.ndim) # Here array is 3 dimensional
print(arr3.dtype)
print(arr3.size)
print(arr3.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 22 55]]]
3
int64
12
(2, 2, 3)


In [57]:
arr4=np.array([12,24,36,48,60,72,84,96,108,120,132,144]) # creating array
print(arr4)
print(arr4[1]) #prints element of an array at index positiion 1 i.e from starting. Indexing starts from 0
print(arr4[-2]) #prints element of an array at index positiion -2 i.e from backwards. Indexing starts from -1

[ 12  24  36  48  60  72  84  96 108 120 132 144]
24
132


In [58]:
store=np.arange(2,11) #arranges the array from 2 to n-1 i.e 10
print(store)

[ 2  3  4  5  6  7  8  9 10]


In [59]:
temp=arr4.reshape(4,3) # reshaping the array4 in 4 rows and 3 columns with its existing elements
print(temp)

[[ 12  24  36]
 [ 48  60  72]
 [ 84  96 108]
 [120 132 144]]


In [64]:
x=np.array([55,29,90])
y=np.array([70,82,99])
print("Addition : ",x+y) # Add two arrays
print("Subtraction : ",x-y) # Subtract two arrays
print("Multiplication : ",x*y) # Multiply two arrays
print("Division : ",x/y) # Divide two arrays
print("Power : ",x**y) # Power of x raised to y

Addition :  [125 111 189]
Subtraction :  [-15 -53  -9]
Multiplication :  [3850 2378 8910]
Division :  [0.78571429 0.35365854 0.90909091]
Power :  [-3093511129017067407  6209081803628514185                    0]


In [61]:
print(arr1)
print(arr1.max()) # prints max element in an array
print(arr1.min()) # prints min element in an array
print(np.argmax(arr1)) # prints index of max element in an array
print(np.argmin(arr1)) # prints index of min element in an array

[1 2 3 4 5 6 7 8 9]
9
1
8
0


In [62]:
print(arr1)
print(np.diff(arr1)) # prints the diffference between two consecutive elements in an array. Here difference is 1 because each element in the array appears serially

[1 2 3 4 5 6 7 8 9]
[1 1 1 1 1 1 1 1]


In [63]:
np.linspace(8,45,num=8) # prints the values assigned to num in the specified range. Here specified range is 8 to 45

array([ 8.        , 13.28571429, 18.57142857, 23.85714286, 29.14285714,
       34.42857143, 39.71428571, 45.        ])