In [14]:
import numpy as np
print(np.__version__)

2.1.3


In [35]:
import numpy as np; print(np.zeros(5, dtype=np.int32))



[0 0 0 0 0]


In [42]:
import numpy as np

arr=np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr)
print(arr.shape)
print(arr.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
int64


In [38]:
import numpy as np; print(np.zeros(5, dtype=float))

[0. 0. 0. 0. 0.]


In [46]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.reshape(2, 3))

[[1 2 3]
 [4 5 6]]


In [53]:
a = np.array([[1, 5], [7, 2]]) 
print(a.max())      


7


In [58]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(np.swapaxes(a, 0, 1)) 

[[1 3]
 [2 4]]


In [67]:
a = np.linspace(0, 1, 5)  
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [63]:
import numpy as np
print(np.ones(5, dtype=np.int32))


[1 1 1 1 1]


In [65]:
import numpy as np
a=np.array([5,7,9,78,1,232,56,6,8,35,2533,67,989,221,34])
print(np.sort(a))

[   1    5    6    7    8    9   34   35   56   67   78  221  232  989
 2533]


In [70]:
import numpy as np

a = np.array([[8, 2, 5],
              [4, 9, 1],
              [7, 6, 3]])

print("Original", a)




Original [[8 2 5]
 [4 9 1]
 [7 6 3]]
Row-wise sort (axis=1) [[2 5 8]
 [1 4 9]
 [3 6 7]]
Column-wise sort (axis=0) [[4 2 1]
 [7 6 3]
 [8 9 5]]
