In [35]:
# NAME : Mishra Mitali Devidas 
# Roll no : 163
# Batch : T1
# Assignmnet No : 1
import numpy as np; print(np.zeros(5, dtype=np.int32))

[0 0 0 0 0]


In [14]:
import numpy as np
print(np.__version__)

2.1.3


In [42]:
import numpy as np

arr=np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr)
print(arr.shape)
print(arr.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
int64


In [38]:
import numpy as np; print(np.zeros(5, dtype=float))

[0. 0. 0. 0. 0.]


In [46]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.reshape(2, 3))

[[1 2 3]
 [4 5 6]]


In [53]:
a = np.array([[1, 5], [7, 2]]) 
print(a.max())      


7


In [58]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
print(np.swapaxes(a, 0, 1)) 

[[1 3]
 [2 4]]


In [67]:
a = np.linspace(0, 1, 5)  
print(a)

[0.   0.25 0.5  0.75 1.  ]


In [63]:
import numpy as np
print(np.ones(5, dtype=np.int32))

[1 1 1 1 1]


In [65]:
import numpy as np
a=np.array([5,7,9,78,1,232,56,6,8,35,2533,67,989,221,34])
print(np.sort(a))

[   1    5    6    7    8    9   34   35   56   67   78  221  232  989
 2533]


In [11]:
import numpy as np
a = np.array([[8, 2, 5], [4, 9, 1], [7, 6, 3]])
print("Original", a)

Original [[8 2 5]
 [4 9 1]
 [7 6 3]]


In [12]:
import numpy as np
arr = np.array([[3, 2, 1],[6, 5, 4],[9, 7, 8]])
print("Original array:\n", arr)
print("\nSort in axis=0:\n", np.sort(arr, axis=0))
print("\nSort in axis=1:\n", np.sort(arr, axis=1))

Original array:
 [[3 2 1]
 [6 5 4]
 [9 7 8]]

Sort in axis=0:
 [[3 2 1]
 [6 5 4]
 [9 7 8]]

Sort in axis=1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
print("max element", np.max(arr))
print("min element", np.min(arr))
print(np.linspace(1, 10, num=5))

max element 9
min element 1
[ 1.    3.25  5.5   7.75 10.  ]


In [16]:
arr1 = np.zeros((4, 3), dtype="int")
print(arr1)
print(arr1.shape)
print(arr1.dtype)
print(arr1.size)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
(4, 3)
int64
12


In [17]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7])
print("Dimension:", array1.ndim)

Dimension: 1


In [18]:
print("Size:", array1.size)

Size: 7


In [19]:
print("Shape:", array1.shape)

Shape: (7,)


In [21]:
print("Second element:", array1[1])

Second element: 2


In [22]:
print("Last element:", array1[-1])

Last element: 7


In [23]:
array1 = np.arange(2, 11)
b = array1.reshape(3, 3)
print(b)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [24]:
x = np.array([[1, 2, 3], [2, 3, 4]])
y = np.array([[10, 11, 12], [13, 14, 15]])
print(x)
print(y)
z = x + y
print("------------------")
print(z)

[[1 2 3]
 [2 3 4]]
[[10 11 12]
 [13 14 15]]
------------------
[[11 13 15]
 [15 17 19]]


In [25]:
z = x - y
print("------------------")
print(z)

------------------
[[ -9  -9  -9]
 [-11 -11 -11]]


In [26]:
z = x * y
print("------------------")
print(z)

------------------
[[10 22 36]
 [26 42 60]]


In [27]:
z = x / y
print("------------------")
print(z)

------------------
[[0.1        0.18181818 0.25      ]
 [0.15384615 0.21428571 0.26666667]]


In [28]:
z = x ** y
print("------------------")
print(z)

------------------
[[         1       2048     531441]
 [      8192    4782969 1073741824]]


In [29]:
arr = np.array([10, 20, 5, 30, 25])
max_index = np.argmax(arr)
print("Index of maximum value:", max_index)
print("Maximum value:", arr[max_index])

Index of maximum value: 3
Maximum value: 30


In [30]:
min_index = np.argmin(arr)
print("Index of minimum value:", min_index)
print("Minimum value:", arr[min_index])

Index of minimum value: 2
Minimum value: 5
